#!/usr/bin/perl -w

my $machines = "," . join(",", @ARGV) . ",";
@ARGV = ();

my $to_print = 1;
while (my $line = <>) {
  if ($line =~ /BEGIN_MACHINE\(([0-9.]+),/) {
    my $machine = ",$1,";
    $to_print = ($machines =~ /$machine/);
  }
  print $line if $to_print;
  $to_print = 1 if ($line =~ /END_MACHINE\(/);
}
